### ISSUE TITLE
Typo in project.json

### ISSUE THREAD

**Issue by CorbinSteele** [flecs-hub/flecs-game#1]
Build error is immediately evident on Linux.

```
"lang.c": {
    "libs": ["m"]
}
```
should be
```
"lang.c": {
    "lib": ["m"]
}
```
or perhaps even
```
"lang.c": {
    "${os linux}": {
        "lib": ["m"]
    }
}
```

I've only tested on Linux, so adapt if needed.
(I'm new to bake, but loving it at first glance.)

**Comment by SanderMertens** [comment]
Oh you're right, thanks for creating the issue. Just checked in a fix!
